architect: extsoft
docker:
  image: yegor256/java8
install: |-
  java -version
  export LC_ALL=en_US.UTF-8
  export LANG=en_US.UTF-8
  export LANGUAGE=en_US.UTF-8
  sudo gem install pdd
merge:
    fast-forward: only
    rebase: true
    script: |-
        ./gradlew 
        ./gradlew clean
        pdd --source=$(pwd) --verbose --file=/dev/null
    commanders:
    - extsoft
    - Mras

release: # @todo #49:3h Add ability to release to Sonatype
    pre: false
    script: echo "Release ${tag}"
    commanders: extsoft
