architect: extsoft
docker:
  image: yegor256/java8
install: |-
  java -version
  export LC_ALL=en_US.UTF-8
  export LANG=en_US.UTF-8
  export LANGUAGE=en_US.UTF-8
  sudo gem install pdd
merge:
    fast-forward: only
    rebase: true
    script: |-
        ./gradlew --info
        ./gradlew clean
        pdd --source=$(pwd) --verbose --file=/dev/null
    commanders:
    - extsoft
    - Mras
decrypt:
  gradle.properties: "repo/scrt/gradle.properties.asc"
  secring.gpg: "repo/scrt/secring.gpg.asc"
release:
  commanders: extsoft
  script: |-
    cp -v ../gradle.properties ../secring.gpg ./
    ./gradlew updateVersion -PnewVersion=${tag}
    ./gradlew clean ready signArchives bintrayUpload --info
