architect: extsoft
docker:
  image: yegor256/java8
install: |-
  java -version
  export LC_ALL=en_US.UTF-8
  export LANG=en_US.UTF-8
  export LANGUAGE=en_US.UTF-8
  sudo gem install pdd
merge:
    fast-forward: only
    rebase: true
    script: |-
        ./gradlew 
        ./gradlew clean
        pdd --source=$(pwd) --verbose --file=/dev/null
    commanders:
    - extsoft
    - Mras
decrypt:
  gradle.properties: "repo/scrt/gradle.properties.asc"
  secring.gpg: "repo/scrt/secring.gpg.asc"
release: # @todo #49:3h Add ability to release to Sonatype
  commanders: extsoft
  script: |-
    cp ../gradle.properties .
    cp ../secring.gpg sunshine-core
    cp ../secring.gpg sunshine-junit4
    cp ../secring.gpg sunshine-testng
    ./gradlew updateVersion -PnewVersion=${tag}
    git commit -am "${tag}"
    ./gradlew -i clean uploadArchives
