language: java
jdk: oraclejdk8
install: true
after_success: bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
  slack:
    rooms:
          - test-automation-tools:CMmRQOwodzTGByyGqAnySHHS#sunshine-robots

script: ./gradlew
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
