language: java
jdk: oraclejdk8
after_success: bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
  slack:
    rooms:
          - test-automation-tools:CMmRQOwodzTGByyGqAnySHHS#sunshine-robots

script: ./gradlew
